version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: feedback-app
      MYSQL_PASSWORD: admin
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
  app:
    build: ./php
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
    environment:
      - APP_ENV=dev